export type PdfCoverageEntry = {
  order: number;
  title: string;
  BurmeseTitle: string;
  sourceTopics: string[];
  originalCoverage: string;
  mappedChapterIds: number[];
};

/**
 * Ordered coverage inventory derived from the user-provided PDF table of contents.
 * The platform uses original Burmese explanations rather than reproducing the
 * source book's protected prose or chapter text verbatim.
 */
export const flutterPdfCoverage: PdfCoverageEntry[] = [
  { order: 1, title: "Welcome", BurmeseTitle: "Flutter လေ့လာရေးသို့ ကြိုဆိုခြင်း", sourceTopics: ["Flutter ရည်ရွယ်ချက်", "စာအုပ်လမ်းကြောင်း", "ဆက်လက်လေ့လာရန် resources"], originalCoverage: "Flutter နှင့် Dart ကို ဘာကြောင့်တွဲသုံးသလဲ၊ လေ့လာသူက project တည်ဆောက်ရာတွင် ဘယ်လိုစဉ်းစားရမလဲနှင့် လေ့လာမှုအဆင့်များကို မိတ်ဆက်ထားသည်။", mappedChapterIds: [1, 31] },
  { order: 2, title: "Basic Terminology", BurmeseTitle: "Mobile နှင့် Cross-platform အခြေခံအသုံးအနှုန်းများ", sourceTopics: ["Mobile applications", "Device platforms", "Development methodologies", "Cross-platform development", "အစောပိုင်း tools", "ခေတ်သစ် tools"], originalCoverage: "Native, cross-platform, framework, SDK, package နှင့် deployment တို့ကို တစ်ခုချင်းခွဲ၍ platform ရွေးချယ်မှု၏ အကျိုးဆက်ကို နားလည်စေသည်။", mappedChapterIds: [1, 6, 31, 46] },
  { order: 3, title: "Introduction To Dart", BurmeseTitle: "Dart Language နှင့် Flutter ဆက်နွယ်မှု", sourceTopics: ["Dart language", "Dart Native", "JIT", "AOT", "Platforms", "Dart SDK", "Flutter development", "Advanced Dart examples"], originalCoverage: "Dart ၏ type system, execution mode, SDK နှင့် Flutter application ထဲတွင် Dart code ၏တာဝန်ကို ရှင်းပြပြီး variable, function, class, asynchronous flow များနှင့်ချိတ်ဆက်ထားသည်။", mappedChapterIds: [1, 2, 3, 4, 5, 21, 22, 23, 24, 25, 26] },
  { order: 4, title: "Introduction To Flutter", BurmeseTitle: "Flutter Framework နှင့် Release Channels", sourceTopics: ["Flutter", "Flutter source code", "Flutter framework", "Release process", "Channels", "Stable/Beta/Main", "Channel change"], originalCoverage: "Flutter engine, framework, widget layer, stable channel ရွေးချယ်မှုနှင့် version update မလုပ်မီ စစ်ဆေးရမည့် compatibility အချက်များကို ရှင်းပြသည်။", mappedChapterIds: [6, 18, 20, 31, 33, 45] },
  { order: 5, title: "Installing Flutter 2.2", BurmeseTitle: "Flutter Development Environment ပြင်ဆင်ခြင်း", sourceTopics: ["Flutter SDK", "PC နှင့် iOS development", "Software requirements", "Android Studio", "Visual Studio Code", "macOS setup", "Path", "Flutter Doctor"], originalCoverage: "SDK installation, PATH, editor, emulator/device, Flutter Doctor နှင့် platform toolchain ကို project မစခင် စစ်ဆေးပုံကို လက်တွေ့အဆင့်များအဖြစ် ရေးထားသည်။", mappedChapterIds: [21, 31, 32, 45] },
  { order: 6, title: "Flutter Project 1 - Build Your First App", BurmeseTitle: "ပထမဆုံး Flutter App တည်ဆောက်ခြင်း", sourceTopics: ["Create project", "Package name", "Project structure", "Default app", "main.dart", "Run app"], originalCoverage: "Project ဖန်တီးခြင်းမှ package identity, lib/test folders, main.dart, run configuration နှင့် default counter app ကိုဖတ်တတ်သည်အထိ တည်ဆောက်ပေးသည်။", mappedChapterIds: [6, 31, 32, 33] },
  { order: 7, title: "Flutter Project 2 - Build a Song App", BurmeseTitle: "Song Player App တည်ဆောက်ခြင်း", sourceTopics: ["Packages", "Internet audio", "Asset audio", "External storage", "Audio setup", "Control panel", "SongDuration", "SongProgress"], originalCoverage: "Package ရွေးချယ်မှု၊ asset နှင့် remote audio၊ playback state၊ seek bar၊ duration/progress နှင့် play/pause control တို့ကို feature flow တစ်ခုအဖြစ် ရှင်းပြသည်။", mappedChapterIds: [15, 17, 30, 38, 41, 42] },
  { order: 8, title: "Flutter Project 3 - Build a Login UI", BurmeseTitle: "Login UI ကို တည်ဆောက်ခြင်း", sourceTopics: ["Assets", "Images", "Text fields", "Validation", "Login layout", "Responsive UI"], originalCoverage: "Asset ထည့်သွင်းခြင်း၊ input field, validation feedback, keyboard behavior နှင့် login screen ကို responsive ဖြစ်အောင် စီစဉ်ပုံကို မူရင်း code ဖြင့် သင်ကြားသည်။", mappedChapterIds: [8, 9, 11, 13, 19, 30] },
  { order: 9, title: "Flutter Project 4 - Build a Name Generator", BurmeseTitle: "Name Generator App တည်ဆောက်ခြင်း", sourceTopics: ["Environment", "Starter app", "Third-party package", "StatefulWidget", "Infinite ListView", "Icons", "Interactivity", "Navigation", "Themes"], originalCoverage: "Package တစ်ခုမှ generated data ရယူခြင်း၊ StatefulWidget ဖြင့် list state ထိန်းခြင်း၊ infinite scrolling, favorite action, detail navigation နှင့် theme ပြောင်းခြင်းကို project အဖြစ်ဖော်ပြသည်။", mappedChapterIds: [8, 10, 11, 12, 16, 25, 28, 29, 30, 37, 41] },
  { order: 10, title: "Flutter Project 5 - Build an Ecommerce App", BurmeseTitle: "Ecommerce App အခြေခံတည်ဆောက်ခြင်း", sourceTopics: ["Environment", "Project creation", "Package import", "main.dart", "Product UI", "Cart flow"], originalCoverage: "Product model, catalog layout, package integration, cart state နှင့် reusable UI ကို feature တစ်ခုချင်း ခွဲပြီး production-minded မူရင်း implementation အဖြစ် ချဲ့ထွင်သည်။", mappedChapterIds: [12, 13, 14, 17, 18, 30, 42, 43, 46] },
  { order: 11, title: "FlutterFlow Project 1 - Build a Threefold Pricing Scroll", BurmeseTitle: "FlutterFlow Pricing Scroll အယူအဆ", sourceTopics: ["Environment", "New page", "Widget positioning", "Pricing cards", "Scrolling interaction"], originalCoverage: "Low-code design tool ၏ page, widget tree, responsive positioning နှင့် pricing card scroll အယူအဆကို Flutter code architecture နှင့် နှိုင်းယှဉ်နားလည်စေသည်။", mappedChapterIds: [7, 11, 35, 51] },
  { order: 12, title: "FlutterFlow Project 2 - Build a Chat App", BurmeseTitle: "Chat App Flow နှင့် Realtime UI", sourceTopics: ["Prerequisites", "Chat layout", "Messages", "Input composer", "Backend connection"], originalCoverage: "Chat screen ၏ message list, composer, loading/error state, realtime data နှင့် permission စဉ်းစားပုံကို Flutter implementation နှင့် ချိတ်ဆက်သည်။", mappedChapterIds: [12, 13, 16, 17, 18, 28, 42] },
  { order: 13, title: "Flutter and HTTP", BurmeseTitle: "Flutter နှင့် HTTP Communication", sourceTopics: ["Asynchronous communication", "HTTP", "Tools", "Methods", "URL", "Query parameters", "Matrix parameters", "Path parameters", "Status", "Header", "Body", "Request", "Response"], originalCoverage: "HTTP request ၏ method, URL, parameter, header, body, status code နှင့် response parsing ကို Future/async state, retry, error mapping နှင့် screen UI ထဲတွင် အစအဆုံး ချိတ်ဆက်ရှင်းပြသည်။", mappedChapterIds: [5, 13, 16, 17, 18, 24, 42, 55] },
  { order: 14, title: "Debugging", BurmeseTitle: "Flutter Debugging နှင့် Error ရှာဖွေခြင်း", sourceTopics: ["Flutter debugging", "Code implementation", "Debugging tools", "Assertions", "DevTools", "Logs"], originalCoverage: "Compile error, runtime error, layout overflow, async failure နှင့် logic bug ကို ခွဲခြားပြီး debugger, logs, assertions, inspector နှင့် profiling tools အသုံးပြုနည်းကို ရှင်းပြသည်။", mappedChapterIds: [19, 24, 45, 50, 56] },
  { order: 15, title: "Other Considerations", BurmeseTitle: "Production အတွက် ထပ်မံစဉ်းစားရမည့်အချက်များ", sourceTopics: ["HTTP communication", "Data considerations", "Security", "Privacy", "Offline/cache", "Error handling"], originalCoverage: "Network failure, data model, caching, privacy, secret များမပေါက်စေရေး၊ server validation နှင့် user trust ကို app architecture ထဲတွင် အစကတည်းကထည့်သွင်းစဉ်းစားသည်။", mappedChapterIds: [14, 17, 18, 43, 44, 55, 56] },
  { order: 16, title: "Publishing Your App", BurmeseTitle: "Flutter App ကို iOS နှင့် Android ထုတ်ဝေခြင်း", sourceTopics: ["Release process", "iOS release", "Android release", "Build modes", "Signing", "Store submission", "Post-release monitoring"], originalCoverage: "Release configuration, build mode, signing, platform metadata, store submission checklist, rollback နှင့် release နောက်ပိုင်း monitoring ကို production checklist အဖြစ် စုစည်းသည်။", mappedChapterIds: [20, 39, 40, 46, 47, 51, 52, 54, 56] },
];

export const flutterPdfTopicCount = flutterPdfCoverage.reduce((total, entry) => total + entry.sourceTopics.length, 0);

export function pdfTopicsForChapter(chapterId: number): string[] {
  return flutterPdfCoverage
    .filter((entry) => entry.mappedChapterIds.includes(chapterId))
    .flatMap((entry) => [entry.title, entry.BurmeseTitle, ...entry.sourceTopics, entry.originalCoverage]);
}
